//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AsanShahrDBEntities : DbContext
    {
        public AsanShahrDBEntities()
            : base("name=AsanShahrDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Owners> Owners { get; set; }
        public virtual DbSet<RealestateOwners> RealestateOwners { get; set; }
        public virtual DbSet<Realestates> Realestates { get; set; }
        public virtual DbSet<vwRealestateOwners> vwRealestateOwners { get; set; }
    }
}
