//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealestateOwners
    {
        public long ID { get; set; }
        public long RealestateID { get; set; }
        public long OwnerID { get; set; }
    
        public virtual Owners Owners { get; set; }
        public virtual Realestates Realestates { get; set; }
    }
}
